
;===================================================
;			RAM Define
;====================================================

;===================================================
;			Module Define
;====================================================
.EXTERN         F_ClrLcdDpram
.EXTERN			F_AllDisplayLcd
.EXTERN         F_ClrPage0SRAM
.EXTERN         F_ClrSRAM
.EXTERN         F_Display
.EXTERN			F_DisplayNum

.EXTERN		F_ByteHLValue
.EXTERN		F_ByteLHValue
.EXTERN		F_TestModeCnt
.EXTERN		F_DisplayBatIcon
;.extern			F_CheckWakeLEDInc

.EXTERN			R_TempBuf
;====================================================

